### ISSUE TITLE
TypeError: must be str, not bytes python 3.4 ubuntu server

### ISSUE THREAD

**Issue by cresg820** [landscapeio/prospector#104]
I've installed prospector in a virtualenv with:
   `pip install prospector`

I want to use it with my django project and from django root(where manage.py is) if i run
   `prospector`

i get the following error
    
    File ".....................env/bin/prospector", line 9, in <module>
         load_entry_point('prospector==0.9.6', 'console_scripts', 'prospector')()
    File "....................env/lib/python3.4/site-packages/prospector/run.py", line 139, in main
         prospector.print_messages()
    File "....................env/lib/python3.4/site-packages/prospector/run.py", line 111, in print_messages
         ).encode('utf-8'))
    TypeError: must be str, not bytes

**Comment by carlio** [comment]
This should be fixed in the 0.9.7 release, thanks for the report! I think the bug is a combination of filesystem encoding and filenames so I am not 100% certain I fixed it.

**Comment by cresg820** [comment]
@carlio thanks for the immediate response
I've updated and now it works!

**Comment by carlio** [comment]
Good to hear, thanks!
