### ISSUE TITLE
pkg_resources.DistributionNotFound: logilab-common>=0.60.0

### ISSUE THREAD

**Issue by oppianmatt** [landscapeio/prospector#113]
pip installed prospector which happened to be prospector-0.9.9

It then raised this error when running without arguments:  `pkg_resources.DistributionNotFound: logilab-common>=0.60.0`

**Comment by carlio** [comment]
This may be fixed as part of #115 (and is similar to #115). I don't really know why it happens yet - please try the new release (0.10.1) in case it helps?

**Comment by carlio** [comment]
#110 seems to be fixed and I assume this is the same bug - please reopen if the new 0.10.1 release doesn't fix it for you.
