### ISSUE TITLE
Using `pylintrc` file

### ISSUE THREAD

**Issue by jakirkham** [landscapeio/prospector#125]
In the documentation of `prospector`, it states that `.pylintrc` is looked for not `pylintrc`. As nice as it would be to have this be a hidden file, `pylint` will not find it by default if it is. Can we ensure that `pylintrc` is looked for?

**Comment by Kriechi** [comment]
This should be the case:
https://github.com/landscapeio/prospector/blob/master/prospector/tools/pylint/__init__.py#L172-178

Do you get an error message - or what kind of behaviour do you expect?

**Comment by bittner** [comment]
The [Landscape documentation](https://docs.landscape.io/advanced.html#existing-configuration) states:

> If you have configuration for `pep8.py` and `pyflakes`, Landscape will use that *but also run pylint with its defaults*.

(Is this only specific to  Landscape? -- Sorry, not using prospector on the command line.)

This is weird and makes things complicated. Why, the hack, if I want Pylint to behave in a certain way I have to configure this a second time also in `.landscape.yml`?

**Comment by carlio** [comment]
@bittner If you have a `.pylintrc` file that will be used. The point is that prospector runs pep8/pyflakes/pylint all together and merges the results, so if you configure pep8 not to warn about something but pylint does, then you will get the warning. There's not really a priority built in (yet).

**Comment by bittner** [comment]
If two tools warn about the same issue that's not an issue. At least not the one that I'm after. But if I disable a warning for Pylint in `pylintrc` (or `.pylintrc`, recently) and Landscape still complains about it that's disturbing.

**Comment by carlio** [comment]
Prospector (and therefore Landscape) will pick up either `pylintrc` or `.pylintrc`, so I think this is ok to close? Feel free to re-open if not! (Just spring-cleaning right now)

**Comment by jakirkham** [comment]
Will try to revisit. I had added a couple PRs sometime back to `pylint`, which made sure it was picking up `.pylintrc` better. Though I know these got accepted I don't know if all of them made it into a release (or if those releases are used on Landscape). Is there a version listing somewhere that would tell me what Landscape is using currently?

**Comment by carlio** [comment]
There isn't actually, and there is already a plan to fix that (someone made this comment already, I plan to add it to the docs). I just upgraded it to use `1.5.6`, it was using `1.5` until quite recently. Seems like the newest version of pylint has your patch or at least some kind of `.pylintrc` search: https://github.com/PyCQA/pylint/blob/master/pylint/config.py#L81  Cheers!
