### ISSUE TITLE
Unused argument 'self'

### ISSUE THREAD

**Issue by cancan101** [landscapeio/prospector#128]
This seems like the wrong message. Perhaps it should say method can be static:
```
31:	def OnReceiveThing(self):
Unused argument 'self'
32:	    print "Thing received"
```

**Comment by carlio** [comment]
Typically static methods don't take `self` as an argument though, and I think you'd get a warning about that if it was marked with `@staticmethod`?  Either way this seems like a particular case rather than a generic one.
