### ISSUE TITLE
Unused argument 'args'

### ISSUE THREAD

**Issue by cancan101** [landscapeio/prospector#129]
This seems extraneous:
```
160:	class ThingViewSet(GenericViewSet):
161:	    @detail_route(methods=['get'])
162:	    def thingy(self, request, *args, **kwargs):
Unused argument 'args'
```

**Comment by carlio** [comment]
You can configure this yourself to ignore that in that particular case, I don't think it's good to turn it off for everything by default - see https://docs.landscape.io/suppressing.html
