### ISSUE TITLE
Possibility of loading extra pylint modules

### ISSUE THREAD

**Issue by adaptivdesign** [landscapeio/prospector#144]
I've been trying out prospector and so far I like it a lot, however I couldn't find a way to load my own pylint plugins. I forked your project and added support for a pylint 'load-plugins' option:

https://github.com/adaptivdesign/prospector/commit/ba17eb793c7bc9d56881a189d2752fb49d64b73c

This is probably a quick and dirty solution. Would it be possible for you to add this feature?

**Comment by carlio** [comment]
You can already have it load extra plugins if you specify them in a `.pylintrc` file (as normal - prospector just adds that pylint configuration when loading, see https://github.com/landscapeio/prospector/blob/master/prospector/tools/pylint/__init__.py#L99)
