### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 5515: character maps to <undefined>

### ISSUE THREAD

**Issue by reactpro** [landscapeio/prospector#148]
![image](https://cloud.githubusercontent.com/assets/4152736/11631616/b3c4b3d0-9d24-11e5-9d13-296189192b13.png)

**Comment by carlio** [comment]
This is probably fixed now, was a bug in `dodgy` rather than prospector, see https://github.com/landscapeio/dodgy/commit/cd23d1713945ad0019cf847c79624b24fa391dd4
