### ISSUE TITLE
pep257 tool reports conflicting messages, D203, D211

### ISSUE THREAD

**Issue by jquast** [landscapeio/prospector#155]
The two errors are seemingly in conflict::

    pep257: D203 / 1 blank line required before class docstring (found 0)
    pep257: D211 / No blank lines allowed before class docstring (found 1)

I believe the default profile should prefer ignoring ``D203`` message category class, beginning pep257 version 0.7.0, ``D203`` is ignored by command-line tool: https://github.com/GreenSteam/pep257/commit/fda0c4158ea85f07198b380207ad2ffc867fb9c3

**Comment by carlio** [comment]
I've just made release 0.12 which uses pydocstyle 1.0 instead of pep257 and it is now the case that D211 is prioritised over D203 by pydocstyle so no need for prospector profile magic :)

**Comment by jbaiter** [comment]
I'm getting this exact error with 1.1.1 :-/

**Comment by chocoelho** [comment]
@jbaiter https://github.com/PyCQA/pydocstyle/issues/141

**Comment by chocoelho** [comment]
It's recommended to disable one of them.
