### ISSUE TITLE
Update Pyroma dep

### ISSUE THREAD

**Issue by wldhx** [landscapeio/prospector#168]
Is there any reason for pyroma being fixed at `<2.0`?

An [important bug regarding PBR/setuptools_scm](https://bitbucket.org/regebro/pyroma/issues/28/pyroma-gives-a-score-of-0-when) has been fixed in `2.0.0b1` (current version is `2.0.2`) and it'd be really nice to have it updated.

In fact, I have it updated it manually for my local projects and it works nicely, so no obvious incompatibility problems in my case.

**Comment by carlio** [comment]
Hmm, can't remember exactly, previously it was just `!=1.8.3` due to some bugs. Can certainly update that, feel free to add a PR or I'll get around to it myself soon

**Comment by wldhx** [comment]
Should I just fix it at >= latest version (`2.0.2`)?

**Comment by carlio** [comment]
Sure, if 2.0.2 is working for you then why not? Can always change it later if incompatabilities becomes apparent with later versions.

**Comment by carlio** [comment]
Cool, thanks for the PR! will get a new release out soon :+1:
