### ISSUE TITLE
no pylint 1.6.x tests/checks

### ISSUE THREAD

**Issue by stdweird** [landscapeio/prospector#183]
when running prospector with pylint 1.6.x installed, no pylint warnings are shown. runing pylint 1.6.x directly shows errors in files, and removing 1.6.x and installing 1.5.6 gives pylint warnings when running prospector.

is prospector supposed to work with pylint 1.6.x? is there anything special required to make it work?

**Comment by astrostl** [comment]
Confirming same issue. Came here after doing some A/B testing between prospector+pylint and pylint. Cross-reference issue: https://github.com/PyCQA/pylint/issues/1075

**Comment by hjoukl** [comment]
Confirming this issue. No pylint messages are shown at all with `pylint==1.6.x` and this is pretty easy to go unnoticed for a new prospector user (like me). Please consider merging one of the the pull requests in the issues referenced here, preferably #193.
