### ISSUE TITLE
https://prospector.landscape.io/ has invalid certificate

### ISSUE THREAD

**Issue by inglesp** [landscapeio/prospector#195]
Trying to access https://prospector.landscape.io/ in Chrome gives big scary warning, with error `NET::ERR_CERT_COMMON_NAME_INVALID` and details "This server could not prove that it is prospector.landscape.io; its security certificate is from *.readthedocs.io. This may be caused by a misconfiguration or an attacker intercepting your connection.".

[This](http://read-the-docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl) looks like it might be useful documentation.

**Comment by tuukkamustonen** [comment]
I guess this should be reported rather at https://github.com/landscapeio/landscape-issues/issues.

**Comment by carlio** [comment]
Finally fixed :-)

**Comment by inglesp** [comment]
Nice one @carlio!
