### ISSUE TITLE
Linux style forward-slash ignore-paths entries not working on Windows

### ISSUE THREAD

**Issue by edmorley** [landscapeio/prospector#203]
**STR:**
1) Create a `.prospector.yaml` that contains an `ignore-paths` section whose entries use Linux style relative paths (ie: contain forward slashes). For example: https://github.com/benoitc/gunicorn/blob/bc20bea7d9a86ebf2bd1cf62766ecc299b940d77/.prospector.yaml#L3-L13
2) Run prospector on Windows

**Expected:**
Prospector converts the linux style paths in `ignore-paths` to windows style paths, and so correctly ignores the files that were meant to be ignored. This allows the same `.prospector.yaml` to be used on both Windows and Linux (like can be done for pep8/pyflakes own config files etc).

**Actual:**
Prospector reports failures in files that should have been ignored. Eg:
https://ci.appveyor.com/project/edmorley/gunicorn/build/1.0.4/job/7ykop2i0c5xys336

Editing `.prospector.yaml` and replacing the forward slashes with back slashes makes prospector start ignoring the files on Windows (though that presumably would similarly cause failures in the other direction).

Tested using Python 2.7.11 / 3.5.2, and prospector 0.12.4.

**Comment by IceflowRE** [comment]
Can confirm this with Python 3.6 and prospector 0.12.7.
