### ISSUE TITLE
pylint 1.7.0 missing UnknownMessage

### ISSUE THREAD

**Issue by matthbak** [landscapeio/prospector#206]
prospector depends on pylint>=1.5.6 however it doesn't appear to be compatible with the just released 1.7.0

(0) matthbak@matthbak-laptop/tmp
$ prospector
Traceback (most recent call last):
  File "/tmp/prospector/bin/prospector", line 7, in <module>
    from prospector.run import main
  File "/tmp/prospector/local/lib/python2.7/site-packages/prospector/run.py", line 8, in <module>
    from prospector import blender, postfilter, tools
  File "/tmp/prospector/local/lib/python2.7/site-packages/prospector/tools/__init__.py", line 7, in <module>
    from prospector.tools.pylint import PylintTool
  File "/tmp/prospector/local/lib/python2.7/site-packages/prospector/tools/pylint/__init__.py", line 7, in <module>
    from pylint.utils import UnknownMessage
ImportError: cannot import name UnknownMessage
(1) matthbak@matthbak-laptop/tmp
$ pip freeze
appdirs==1.4.3
astroid==1.5.1
backports.functools-lru-cache==1.3
configparser==3.5.0
dodgy==0.1.9
editdistance==0.3.1
enum34==1.1.6
isort==4.2.5
lazy-object-proxy==1.2.2
mccabe==0.6.1
packaging==16.8
pep8-naming==0.4.1
prospector==0.12.4
pycodestyle==2.0.0
pydocstyle==1.0.0
pyflakes==1.5.0
pylint==1.7.0
pylint-celery==0.3
pylint-common==0.2.5
pylint-django==0.7.2
pylint-flask==0.5
pylint-plugin-utils==0.2.6
pyparsing==2.2.0
PyYAML==3.12
requirements-detector==0.5.2
setoptconf==0.2.0
singledispatch==3.4.0.3
six==1.10.0
wrapt==1.10.10

**Comment by matthbak** [comment]
The exception has been renamed to UnknownMessageError

**Comment by matthbak** [comment]
Appears to be same as issue #205

**Comment by theoden-dd** [comment]
It seems #205 to be merged, but error still happens.

Please, update on pypi too.

**Comment by Pawamoy** [comment]
#205 is still open, not merged, see the affected file in master: https://github.com/landscapeio/prospector/blob/master/prospector/tools/pylint/collector.py

**Comment by jquast** [comment]
This caused me a lot of grief, so I thought I would share a `requirements.txt` file that works when using prospector with argument `--die-on-tool-error`:

```
prospector
pylint==1.6.5
astroid==1.4.9
```

Also, make sure to use python3.5, as this version of pylint does not support python3.6.

**Comment by Alir3z4** [comment]
I'm getting this on Python 3.6.1
Any workaround to get it working 3.6.x ?
