### ISSUE TITLE
Pollution from encoding.read_py_file()

### ISSUE THREAD

**Issue by souliane** [landscapeio/prospector#210]
This method prints a line per opened data in order to detect SyntaxError:
`print(tokenize.detect_encoding(f.readline))`

Is there a way to detect a bad encoding without leaving the printed lines on stdout? It is really annoying, especially when changing the output format:
`prospector --output-format xunit > xunit.xml`

Then I get all the ('utf-8', [...]) output in my XML file.

**Comment by carlio** [comment]
Ah oops I'm sorry. This is some debug left in. I was rushing a bit to get
out a new release to fix the pylint 1.7 issues. I'll make a new minor
release with things like this cleaned up.

**Comment by souliane** [comment]
Thanks! :)

**Comment by carlio** [comment]
0.12.6 now on PyPI with this fix. Sorry for the stupid issue.
