### ISSUE TITLE
On what branch should we send Pull Requests?

### ISSUE THREAD

**Issue by Pawamoy** [landscapeio/prospector#238]
Should we send PRs on

- [ ] master,
- [ ] develop,
- [ ] develop-cleaned,
- [ ] or develop-messed?

Maybe you could specify this in a CONTRIBUTING file.

**Comment by chocoelho** [comment]
Hi, @Pawamoy. According to the documentation, PRs should be sent to `develop` branch. You can check for more information in https://prospector.landscape.io/en/master/contrib.html.

**Comment by Pawamoy** [comment]
Thank you @chocoelho , sorry for not having checked the docs myself ^^'!

**Comment by chocoelho** [comment]
No worries :smile:
