### ISSUE TITLE
Code comment to ignore/disable/exclude warning

### ISSUE THREAD

**Issue by wernight** [landscapeio/prospector#49]
To ignore a specific error/warning, as Prospector is a collection of tools, it could either:
 - Show in README.md how to exclude warnings for different tools
 - Implement a general prospector warning exclusion (better)

Known exclusion in comment:
- PyLint, usually before a line block: `# pylint: disable=MESSAGE_ID_OR_KEY`
- PEP-8 add at end of line: `# noqa`
- dodgy: ?
-...

**Comment by carlio** [comment]
With the 0.9 release, prospector now recognises "# noqa" comments and suppresses all warnings from all tools on those lines. The specific pylint disabling still works, too.

**Comment by carlio** [comment]
I'll leave this issue open however to remind me to document this properly!

**Comment by wbolster** [comment]
Thanks, @carlio
