### ISSUE TITLE
[BUG] ignore-path is ignored when using explicit_file_mode

### ISSUE THREAD

**Issue by flobz** [landscapeio/prospector#503]
**Describe the bug**
The ignore-path config is ignored when using explicit file node. This is annoying when prospector is started from a pre-commit hook.

**To Reproduce**
1. add "tests" to ignore-paths' in .prospector.yaml
2. call prospector tests/XXX.py

**Expected behavior**
Ignore tests/XXXX/py

**Environment (please complete the following information):**
 - OS: Linux
 - Prospector 1.7.7
 - Python version [e.g. 3.7.12]

I could provide a fix if this behavior is unintentional.

**Comment by carlio** [comment]
Could you try with `1.8.0rc1` ? The 1.8 release contains a big rewrite of finding files and deciding which ones to check, it hopefully will have also fixed this (though not intentionally).

**Comment by flobz** [comment]
Unfortunately it doesn't fix the problem.

**Comment by flobz** [comment]
1.8.0rc1 seem to fix this issue.

**Comment by okuuva** [comment]
Is 1.8.0rc1 available somewhere readily packaged or would one need to checkout the tag and install from source?

**Comment by Pierre-Sassoulas** [comment]
https://pypi.org/project/prospector/1.8.0rc1/ you can install rc version with [the ``--pre`` option of pip](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-pre)
