### ISSUE TITLE
Allow specifying multiple paths as positional arguments

### ISSUE THREAD

**Issue by guykisel** [landscapeio/prospector#61]
This is related to #56. It would be easier to wrap prospector in other tools (such as a git commit hook) if it could accept more than one path at a time.

I'm interested in implementing this myself and submitting it as a pull request, but I wouldn't mind if someone else with more free time does it instead.

**Comment by carlio** [comment]
I merged in #78 and you can now run prospector with

```
prospector file1.py path/to/file2.py ...
```

It will output all messages together followed by a summary. It's sort of equivalent to saying `prospector .` then explicitly ignoring any files you don't want checked.
