### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by simminni** [landscapeio/prospector#66]
When Prospector is run on some python libraries, it simply exit out with message:

"Segmentation fault (core dumped)"

Sample libraries: pygtkspellcheck,  Netzob, GladeBuilder, gtimelog

Please let me know if you need any further information.

**Comment by carlio** [comment]
Do you have any stack traces or any other information? What OS, Python version etc? Does it happen if you run pylint?
